version: '3.7'

services:

  api:
    container_name: api
    build: ../api
    ports:
      - "5001:5000"
    environment:
      - REACT_APP_HOST=${REACT_APP_HOST}

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:80'
