version: '3'

services:

  api:
    container_name: api
    build: ../api
    ports:
      - "5000:5000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: sh -c "npm build && serve -s build -H '0.0.0.0'"
    ports:
      - "3000:3000"
