version: '3.7'

services:

  api:
    container_name: api
    build: ../api
    ports:
      - "5000:5000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'